name: '每日东方project'

on:
  # schedule:
  #   - cron: '0 0 * * *'
  watch:
    types: started
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: 安装依赖库
      run: |
          sudo -H pip3 install --upgrade setuptools
          sudo -H pip3 install -r requirements.txt

    - name: 每日东方project
      run: python3 Article_east.py
      env:
          SESSDATA: ${{ secrets.SESSDATA }}
          BILI_JCT: ${{ secrets.BILI_JCT }}
